field_types_sql = {
    "Reference Pool ID": "VARCHAR(4)",
    "Loan Identifier": "VARCHAR(12)",
    "Monthly Reporting Period": "DATE",
    "Channel": "CHAR(1)",
    "Seller Name": "VARCHAR(50)",
    "Servicer Name": "VARCHAR(50)",
    "Master Servicer": "VARCHAR(10)",
    "Original Interest Rate": "DECIMAL(5, 3)",
    "Current Interest Rate": "DECIMAL(5, 3)",
    "Original UPB": "DECIMAL(12, 2)",
    "UPB at Issuance": "DECIMAL(12, 2)",
    "Current Actual UPB": "DECIMAL(12, 2)",
    "Original Loan Term": "INTEGER",
    "Origination Date": "DATE",
    "First Payment Date": "DATE",
    "Loan Age": "INTEGER",
    "Remaining Months to Legal Maturity": "INTEGER",
    "Remaining Months To Maturity": "INTEGER",
    "Maturity Date": "DATE",
    "Original Loan to Value Ratio (LTV)": "DECIMAL",
    "Original Combined Loan to Value Ratio (CLTV)": "DECIMAL",
    "Number of Borrowers": "INTEGER",
    "Debt-To-Income (DTI)": "DECIMAL",
    "Borrower Credit Score at Origination": "INTEGER",
    "Co-Borrower Credit Score at Origination": "INTEGER",
    "First Time Home Buyer Indicator": "CHAR(1)",
    "Loan Purpose": "CHAR(1)",
    "Property Type": "CHAR(2)",
    "Number of Units": "INTEGER",
    "Occupancy Status": "CHAR(1)",
    "Property State": "CHAR(2)",
    "Metropolitan Statistical Area (MSA)": "VARCHAR(5)",
    "Zip Code Short": "VARCHAR(3)",
    "Mortgage Insurance Percentage": "DECIMAL",
    "Amortization Type": "CHAR(3)",
    "Prepayment Penalty Indicator": "CHAR(1)",
    "Interest Only Loan Indicator": "CHAR(1)",
    "Interest Only First Principal And Interest Payment Date": "DATE",
    "Months to Amortization": "INTEGER",
    "Current Loan Delinquency Status": "CHAR(2)",
    "Loan Payment History": "VARCHAR(48)",
    "Modification Flag": "CHAR(1)",
    "Mortgage Insurance Cancellation Indicator": "CHAR(1)",
    "Zero Balance Code": "CHAR(2)",
    "Zero Balance Effective Date": "DATE",
    "UPB at the Time of Removal": "DECIMAL(12, 2)",
    "Repurchase Date": "DATE",
    "Scheduled Principal Current": "DECIMAL(12, 2)",
    "Total Principal Current": "DECIMAL(12, 2)",
    "Unscheduled Principal Current": "DECIMAL(12, 2)",
    "Last Paid Installment Date": "DATE",
    "Foreclosure Date": "DATE",
    "Disposition Date": "DATE",
    "Foreclosure Costs": "DECIMAL(12, 2)",
    "Property Preservation and Repair Costs": "DECIMAL(12, 2)",
    "Asset Recovery Costs": "DECIMAL(12, 2)",
    "Miscellaneous Holding Expenses and Credits": "DECIMAL(12, 2)",
    "Associated Taxes for Holding Property": "DECIMAL(12, 2)",
    "Net Sales Proceeds": "DECIMAL(12, 2)",
    "Credit Enhancement Proceeds": "DECIMAL(12, 2)",
    "Repurchase Make Whole Proceeds": "DECIMAL(12, 2)",
    "Other Foreclosure Proceeds": "DECIMAL(12, 2)",
    "Modification-Related Non-Interest Bearing UPB": "DECIMAL(12, 2)",
    "Principal Forgiveness Amount": "DECIMAL(12, 2)",
    "Original List Start Date": "DATE",
    "Original List Price": "DECIMAL(12, 2)",
    "Current List Start Date": "DATE",
    "Current List Price": "DECIMAL(12, 2)",
    "Borrower Credit Score At Issuance": "INTEGER",
    "Co-Borrower Credit Score At Issuance": "INTEGER",
    "Borrower Credit Score Current": "INTEGER",
    "Co-Borrower Credit Score Current": "INTEGER",
    "Mortgage Insurance Type": "CHAR(1)",
    "Servicing Activity Indicator": "CHAR(1)",
    "Current Period Modification Loss Amount": "DECIMAL(12, 2)",
    "Cumulative Modification Loss Amount": "DECIMAL(12, 2)",
    "Current Period Credit Event Net Gain or Loss": "DECIMAL(12, 2)",
    "Cumulative Credit Event Net Gain or Loss": "DECIMAL(12, 2)",
    "Special Eligibility Program": "CHAR(1)",
    "Foreclosure Principal Write-off Amount": "DECIMAL(12, 2)",
    "Relocation Mortgage Indicator": "CHAR(1)",
    "Zero Balance Code Change Date": "DATE",
    "Loan Holdback Indicator": "CHAR(1)",
    "Loan Holdback Effective Date": "DATE",
    "Delinquent Accrued Interest": "DECIMAL(12, 2)",
    "Property Valuation Method": "CHAR(1)",
    "High Balance Loan Indicator": "CHAR(1)",
    "ARM Initial Fixed-Rate Period ≤ 5 YR Indicator": "CHAR(1)",
    "ARM Product Type": "VARCHAR(100)",
    "Initial Fixed-Rate Period": "INTEGER",
    "Interest Rate Adjustment Frequency": "INTEGER",
    "Next Interest Rate Adjustment Date": "DATE",
    "Next Payment Change Date": "DATE",
    "Index": "VARCHAR(100)",
    "ARM Cap Structure": "VARCHAR(10)",
    "Initial Interest Rate Cap Up Percent": "DECIMAL(4, 4)",
    "Periodic Interest Rate Cap Up Percent": "DECIMAL(4, 4)",
    "Lifetime Interest Rate Cap Up Percent": "DECIMAL(4, 4)",
    "Mortgage Margin": "DECIMAL(4, 4)",
    "ARM Balloon Indicator": "CHAR(1)",
    "ARM Plan Number": "VARCHAR(200)",
    "Borrower Assistance Plan": "CHAR(1)",
    "High Loan to Value (HLTV) Refinance Option Indicator": "CHAR(1)",
    "Deal Name": "VARCHAR(200)",
    "Repurchase Make Whole Proceeds Flag": "CHAR(1)",
    "Alternative Delinquency Resolution": "CHAR(1)",
    "Alternative Delinquency Resolution Count": "INTEGER",
    "Total Deferral Amount": "DECIMAL(12, 2)",
    "Payment Deferral Modification Event Indicator": "CHAR(1)",
    "Interest Bearing UPB": "DECIMAL(12, 2)"
}
field_types_python = {
            "Reference Pool ID": "str",
            "Loan Identifier": "str",
            "Monthly Reporting Period": "datetime64[ns]",
            "Channel": "str",
            "Seller Name": "str",
            "Servicer Name": "str",
            "Master Servicer": "str",
            "Original Interest Rate": "float",
            "Current Interest Rate": "float",
            "Original UPB": "float",
            "UPB at Issuance": "float",
            "Current Actual UPB": "float",
            "Original Loan Term": "int32",
            "Origination Date": "datetime64[ns]",
            "First Payment Date": "datetime64[ns]",
            "Loan Age": "int32",
            "Remaining Months to Legal Maturity": "int32",
            "Remaining Months To Maturity": "int32",
            "Maturity Date": "datetime64[ns]",
            "Original Loan to Value Ratio (LTV)": "float",
            "Original Combined Loan to Value Ratio (CLTV)": "float",
            "Number of Borrowers": "int32",
            "Debt-To-Income (DTI)": "float",
            "Borrower Credit Score at Origination": "int32",
            "Co-Borrower Credit Score at Origination": "int32",
            "First Time Home Buyer Indicator": "str",
            "Loan Purpose": "str",
            "Property Type": "str",
            "Number of Units": "int32",
            "Occupancy Status": "str",
            "Property State": "str",
            "Metropolitan Statistical Area (MSA)": "str",
            "Zip Code Short": "str",
            "Mortgage Insurance Percentage": "float",
            "Amortization Type": "str",
            "Prepayment Penalty Indicator": "str",
            "Interest Only Loan Indicator": "str",
            "Interest Only First Principal And Interest Payment Date": "datetime64[ns]",
            "Months to Amortization": "int32",
            "Current Loan Delinquency Status": "str",
            "Loan Payment History": "str",
            "Modification Flag": "str",
            "Mortgage Insurance Cancellation Indicator": "str",
            "Zero Balance Code": "str",
            "Zero Balance Effective Date": "datetime64[ns]",
            "UPB at the Time of Removal": "float",
            "Repurchase Date": "datetime64[ns]",
            "Scheduled Principal Current": "float",
            "Total Principal Current": "float",
            "Unscheduled Principal Current": "float",
            "Last Paid Installment Date": "datetime64[ns]",
            "Foreclosure Date": "datetime64[ns]",
            "Disposition Date": "datetime64[ns]",
            "Foreclosure Costs": "float",
            "Property Preservation and Repair Costs": "float",
            "Asset Recovery Costs": "float",
            "Miscellaneous Holding Expenses and Credits": "float",
            "Associated Taxes for Holding Property": "float",
            "Net Sales Proceeds": "float",
            "Credit Enhancement Proceeds": "float",
            "Repurchase Make Whole Proceeds": "float",
            "Other Foreclosure Proceeds": "float",
            "Modification-Related Non-Interest Bearing UPB": "float",
            "Principal Forgiveness Amount": "float",
            "Original List Start Date": "datetime64[ns]",
            "Original List Price": "float",
            "Current List Start Date": "datetime64[ns]",
            "Current List Price": "float",
            "Borrower Credit Score At Issuance": "int32",
            "Co-Borrower Credit Score At Issuance": "int32",
            "Borrower Credit Score Current": "int32",
            "Co-Borrower Credit Score Current": "int32",
            "Mortgage Insurance Type": "str",
            "Servicing Activity Indicator": "str",
            "Current Period Modification Loss Amount": "float",
            "Cumulative Modification Loss Amount": "float",
            "Current Period Credit Event Net Gain or Loss": "float",
            "Cumulative Credit Event Net Gain or Loss": "float",
            "Special Eligibility Program": "str",
            "Foreclosure Principal Write-off Amount": "float",
            "Relocation Mortgage Indicator": "str",
            "Zero Balance Code Change Date": "datetime64[ns]",
            "Loan Holdback Indicator": "str",
            "Loan Holdback Effective Date": "datetime64[ns]",
            "Delinquent Accrued Interest": "float",
            "Property Valuation Method": "str",
            "High Balance Loan Indicator": "str",
            "ARM Initial Fixed-Rate Period ≤ 5 YR Indicator": "str",
            "ARM Product Type": "str",
            "Initial Fixed-Rate Period": "int32",
            "Interest Rate Adjustment Frequency": "int32",
            "Next Interest Rate Adjustment Date": "datetime64[ns]",
            "Next Payment Change Date": "datetime64[ns]",
            "Index": "str",
            "ARM Cap Structure": "str",
            "Initial Interest Rate Cap Up Percent": "float",
            "Periodic Interest Rate Cap Up Percent": "float",
            "Lifetime Interest Rate Cap Up Percent": "float",
            "Mortgage Margin": "float",
            "ARM Balloon Indicator": "str",
            "ARM Plan Number": "str",
            "Borrower Assistance Plan": "str",
            "High Loan to Value (HLTV) Refinance Option Indicator": "str",
            "Deal Name": "str",
            "Repurchase Make Whole Proceeds Flag": "str",
            "Alternative Delinquency Resolution": "str",
            "Alternative Delinquency Resolution Count": "int32",
            "Total Deferral Amount": "float",
            "Payment Deferral Modification Event Indicator": "str",
            "Interest Bearing UPB": "float"
        }

column_names = [key for key,value in field_types_python.items()]

sqlite3_schema = {
    "Reference Pool ID": "TEXT",
    "Loan Identifier": "TEXT",
    "Monthly Reporting Period": "TEXT",  # Could be DATE in some contexts
    "Channel": "TEXT",
    "Seller Name": "TEXT",
    "Servicer Name": "TEXT",
    "Master Servicer": "TEXT",
    "Original Interest Rate": "REAL",
    "Current Interest Rate": "REAL",
    "Original UPB": "REAL",
    "UPB at Issuance": "REAL",
    "Current Actual UPB": "REAL",
    "Original Loan Term": "INTEGER",
    "Origination Date": "TEXT",
    "First Payment Date": "TEXT",
    "Loan Age": "INTEGER",
    "Remaining Months to Legal Maturity": "INTEGER",
    "Remaining Months To Maturity": "INTEGER",
    "Maturity Date": "TEXT",
    "Original Loan to Value Ratio (LTV)": "REAL",
    "Original Combined Loan to Value Ratio (CLTV)": "REAL",
    "Number of Borrowers": "INTEGER",
    "Debt-To-Income (DTI)": "REAL",
    "Borrower Credit Score at Origination": "INTEGER",
    "Co-Borrower Credit Score at Origination": "INTEGER",
    "First Time Home Buyer Indicator": "TEXT",
    "Loan Purpose": "TEXT",
    "Property Type": "TEXT",
    "Number of Units": "INTEGER",
    "Occupancy Status": "TEXT",
    "Property State": "TEXT",
    "Metropolitan Statistical Area (MSA)": "TEXT",
    "Zip Code Short": "TEXT",
    "Mortgage Insurance Percentage": "REAL",
    "Amortization Type": "TEXT",
    "Prepayment Penalty Indicator": "TEXT",
    "Interest Only Loan Indicator": "TEXT",
    "Interest Only First Principal And Interest Payment Date": "TEXT",
    "Months to Amortization": "INTEGER",
    "Current Loan Delinquency Status": "TEXT",
    "Loan Payment History": "TEXT",
    "Modification Flag": "TEXT",
    "Mortgage Insurance Cancellation Indicator": "TEXT",
    "Zero Balance Code": "TEXT",
    "Zero Balance Effective Date": "TEXT",
    "UPB at the Time of Removal": "REAL",
    "Repurchase Date": "TEXT",
    "Scheduled Principal Current": "REAL",
    "Total Principal Current": "REAL",
    "Unscheduled Principal Current": "REAL",
    "Last Paid Installment Date": "TEXT",
    "Foreclosure Date": "TEXT",
    "Disposition Date": "TEXT",
    "Foreclosure Costs": "REAL",
    "Property Preservation and Repair Costs": "REAL",
    "Asset Recovery Costs": "REAL",
    "Miscellaneous Holding Expenses and Credits": "REAL",
    "Associated Taxes for Holding Property": "REAL",
    "Net Sales Proceeds": "REAL",
    "Credit Enhancement Proceeds": "REAL",
    "Repurchase Make Whole Proceeds": "REAL",
    "Other Foreclosure Proceeds": "REAL",
    "Modification-Related Non-Interest Bearing UPB": "REAL",
    "Principal Forgiveness Amount": "REAL",
    "Original List Start Date": "TEXT",
    "Original List Price": "REAL",
    "Current List Start Date": "TEXT",
    "Current List Price": "REAL",
    "Borrower Credit Score At Issuance": "INTEGER",
    "Co-Borrower Credit Score At Issuance": "INTEGER",
    "Borrower Credit Score Current": "INTEGER",
    "Co-Borrower Credit Score Current": "INTEGER",
    "Mortgage Insurance Type": "TEXT",
    "Servicing Activity Indicator": "TEXT",
    "Current Period Modification Loss Amount": "REAL",
    "Cumulative Modification Loss Amount": "REAL",
    "Current Period Credit Event Net Gain or Loss": "REAL",
    "Cumulative Credit Event Net Gain or Loss": "REAL",
    "Special Eligibility Program": "TEXT",
    "Foreclosure Principal Write-off Amount": "REAL",
    "Relocation Mortgage Indicator": "TEXT",
    "Zero Balance Code Change Date": "TEXT",
    "Loan Holdback Indicator": "TEXT",
    "Loan Holdback Effective Date": "TEXT",
    "Delinquent Accrued Interest": "REAL",
    "Property Valuation Method": "TEXT",
    "High Balance Loan Indicator": "TEXT",
    "ARM Initial Fixed-Rate Period ≤ 5 YR Indicator": "TEXT",
    "ARM Product Type": "TEXT",
    "Initial Fixed-Rate Period": "INTEGER",
    "Interest Rate Adjustment Frequency": "INTEGER",
    "Next Interest Rate Adjustment Date": "TEXT",
    "Next Payment Change Date": "TEXT",
    "Index": "TEXT",
    "ARM Cap Structure": "TEXT",
    "Initial Interest Rate Cap Up Percent": "REAL",
    "Periodic Interest Rate Cap Up Percent": "REAL",
    "Lifetime Interest Rate Cap Up Percent": "REAL",
    "Mortgage Margin": "REAL",
    "ARM Balloon Indicator": "TEXT",
    "ARM Plan Number": "TEXT",
    "Borrower Assistance Plan": "TEXT",
    "High Loan to Value (HLTV) Refinance Option Indicator": "TEXT",
    "Deal Name": "TEXT",
    "Repurchase Make Whole Proceeds Flag": "TEXT",
    "Alternative Delinquency Resolution": "TEXT",
    "Alternative Delinquency Resolution Count": "INTEGER",
    "Total Deferral Amount": "REAL",
    "Payment Deferral Modification Event Indicator": "TEXT",
    "Interest Bearing UPB": "REAL"
}